/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Form;

import dichVuTam.DVTamRepository;
import dichVuTam.DvTam;
import entity.Dich_Vu;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repository.DichVuRepsitory;
import repository.HDCTRepository;
import repository.LichHenRepository;
import response.HDCTResponse;

/**
 *
 * @author admin
 */
public class AddDVTam extends javax.swing.JDialog {

    DatLich1 dl;
    private DichVuRepsitory dvRepo = new DichVuRepsitory();
    DefaultTableModel dtmDichVu = new DefaultTableModel();
    LichHenRepository lhRepo = new LichHenRepository();
    HDCTRepository hdctRepo = new HDCTRepository();
    DVTamRepository dvTam = new DVTamRepository();
    int viTri;

    /**
     * Creates new form AddDVTam
     */
    public AddDVTam(DatLich1 datLich, boolean modal) {
        this.dl = datLich;
        initComponents();
        setLocationRelativeTo(null);
        dtmDichVu = (DefaultTableModel) tblDichVu.getModel();
        this.showTableDichVu(dvRepo.getAll());

    }

    private void showTableDichVu(ArrayList<Dich_Vu> lists) {
        dtmDichVu.setRowCount(0);
        AtomicInteger index = new AtomicInteger(1);
        lists.forEach(s -> dtmDichVu.addRow(new Object[]{
            index.getAndIncrement(),
            s.getTen_DV(), s.getThoiGianDV(), s.getGia_Tien()
           
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        btnThemDv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Dịch vụ", "Thời Gian", "Giá Tiền "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        btnThemDv.setText("Thêm");
        btnThemDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemDv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnThemDv)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDvActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Bạn yêu muốn gì");
        if (i == JOptionPane.YES_OPTION) {
            viTri = tblDichVu.getSelectedRow();
            if (viTri == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ cần thêm");
                return;
            } else {
                int id  = dvRepo.getAll().get(viTri).getId();
                String ma = dvRepo.getAll().get(viTri).getMa_DV();
                String ten = dvRepo.getAll().get(viTri).getTen_DV();
                String tg =String.valueOf(dvRepo.getAll().get(viTri).getThoiGianDV());
                double gia =dvRepo.getAll().get(viTri).getGia_Tien();
                dvTam.add(new DvTam(id, ma, ten, tg, gia));
                dl.showTableAddDv(dvTam.getAll());
                
                dispose();
                
            }

        }
    }//GEN-LAST:event_btnThemDvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDVTam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDVTam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDVTam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDVTam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDVTam dialog = new AddDVTam(new DatLich1(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemDv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDichVu;
    // End of variables declaration//GEN-END:variables

}
