/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Form;

import Form.View_ThanhToan;
import entity.Dich_Vu;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import response.HDCTResponse;
import repository.DichVuRepsitory;
import repository.HDCTRepository;
import repository.LichHenRepository;

/**
 *
 * @author Admin
 */
public class AddDV extends javax.swing.JDialog {

    private DichVuRepsitory dvRepo = new DichVuRepsitory();
    DefaultTableModel dtmDichVu = new DefaultTableModel();
    LichHenRepository lhRepo = new LichHenRepository();
    HDCTRepository hdctRepo = new HDCTRepository();

    View_ThanhToan viewThanhToan;
    int viTri;

    /**
     * Creates new form AddDV
     */
    public AddDV(View_ThanhToan thanhToan, boolean modal) {
        this.viewThanhToan = thanhToan;

        initComponents();
        setLocationRelativeTo(null);
        dtmDichVu = (DefaultTableModel) tblDichVu.getModel();
        showTableDichVu(dvRepo.getAll());
    }

    private void showTableDichVu(ArrayList<Dich_Vu> lists) {
        dtmDichVu.setRowCount(0);
        AtomicInteger index = new AtomicInteger(1);
        lists.forEach(s -> dtmDichVu.addRow(new Object[]{
            index.getAndIncrement(), 
            
            s.getMa_DV(),
            s.getTen_DV(),
            s.getThoiGianDV(), 
            s.getGia_Tien() + "đ",
            s.getId_LoaiDV(), 
            s.getTrangThai() == 1 ? "Đang Phục Vụ" : "Ngừng Phục Vụ"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThemDv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã dịch vụ", "Tên Dịch vụ", "Thời Gian", "Giá Tiền ", "Loại Dịch Vụ", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Dịch Vụ");

        btnThemDv.setText("Thêm");
        btnThemDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThemDv)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnThemDv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDvActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Xác Nhận Thêm");
        if (i == JOptionPane.YES_OPTION) {
            viTri = tblDichVu.getSelectedRow();
            if (viTri == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ cần thêm");
                return;
            } else {
                
                int idHD = viewThanhToan.SelectedIdHD();
                int idDV = dvRepo.getAll().get(viTri).getId();
                int luot;
                int luotDung;
                boolean foud = false;
                for (HDCTResponse hdct : hdctRepo.getAllHDCTTT(idHD)) {
                    if (hdct.getIdDV() == idDV) {
                        luot = hdct.getSoLuong();
                        luotDung = luot += 1;
                        hdctRepo.UpdateSLHDCT(idHD, idDV, luotDung);
                        viewThanhToan.showTableHDCT(hdctRepo.getAllHDCTTT(idHD));
                        JOptionPane.showMessageDialog(this, "Đã thêm dịch vụ");
                        viTri = 1;
                        viewThanhToan.ShowDetail();
                        foud = true;
                        dispose();
                        break;
                    }
                }

                if (!foud) {
                    hdctRepo.AddHDCT(idHD, idDV);
                    viewThanhToan.showTableHDCT(hdctRepo.getAllHDCTTT(idHD));
                    JOptionPane.showMessageDialog(this, "Đã thêm dịch vụ");
                    viTri = 1;
                    viewThanhToan.ShowDetail();
                    dispose();
                }
                if (idHD == -1) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng ở bảng Lịch hẹn");
                    return;
                }

            }
        } else {
            dispose();
        }


    }//GEN-LAST:event_btnThemDvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDV dialog = new AddDV(new View_ThanhToan(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemDv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDichVu;
    // End of variables declaration//GEN-END:variables
}
