/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import repository.LichHenRepository;
import response.LichHenResponse;

/**
 *
 * @author default
 */
public class KhachHang_History extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();

    private LichHenRepository repo = new LichHenRepository();

    /**
     * Creates new form khachHang1
     */
    public KhachHang_History() {
        initComponents();

        FillTable(repo.LichSuDatLich());
    }

    public void FillTable(ArrayList<LichHenResponse> listkh) {
        dtm = (DefaultTableModel) tblLichHen.getModel();
        dtm.setRowCount(0);

        AtomicInteger index = new AtomicInteger(1);
        Collections.reverse(listkh);

        listkh.forEach(s -> dtm.addRow(new Object[]{
            index.getAndIncrement(),
            s.getTen_KH(),
            s.getNgayHen(),
            s.getGioHen(),
            s.getTen_DV(),
            s.getTen_NV(),
            s.getSdt_KH(),
            s.getThanhTien(),
            s.getGhiChu(),
            (s.getTrangThai() == 1) ? "Đang chờ"
            : (s.getTrangThai() == 2) ? "Đã hủy" : "Đã hoàn thành",}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichHen = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setToolTipText("Bảng lịch sử hẹn");

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLichHen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên khách hàng", "Ngày hẹn", "Giờ hẹn", "Dịch vụ", "Nhân viên", "SDT", "Tổng tiền", "Ghi chú", "Trạng thái"
            }
        ));
        tblLichHen.setToolTipText("");
        tblLichHen.setRowHeight(40);
        tblLichHen.setSelectionBackground(new java.awt.Color(129, 236, 189));
        jScrollPane1.setViewportView(tblLichHen);
        if (tblLichHen.getColumnModel().getColumnCount() > 0) {
            tblLichHen.getColumnModel().getColumn(4).setMinWidth(300);
            tblLichHen.getColumnModel().getColumn(4).setMaxWidth(500);
        }

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1213, 338));
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 101, 274, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jButton2.setText("Tìm kiếm");
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 101, -1, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xls.png"))); // NOI18N
        jButton5.setText("Xuất Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 130, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Lịch sử lịch hẹn");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 300, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void openFile(String flie) {
        try {
            File path = new File(flie);
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = (Sheet) wb.createSheet("customer");
                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblLichHen.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblLichHen.getColumnName(i));
                }

                for (int i = 0; i < tblLichHen.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < tblLichHen.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        if (tblLichHen.getValueAt(i, j) != null) {
                            cell.setCellValue(tblLichHen.getValueAt(i, j).toString());
                        }
                    }
                }

                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());

            } else {
                JOptionPane.showMessageDialog(null, " Xuất file exle thất bại");
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException io) {
            io.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblLichHen;
    // End of variables declaration//GEN-END:variables
}
